mandatoryAccounts:
  - name: Management
    description: >-
      The management (primary) account. Do not change the name field for this
      mandatory account. Note, the account name key does not need to match the
      AWS account name.
    email: ndx-try-provider+gds-ndx-try-aws@dsit.gov.uk
    organizationalUnit: Root
    warm: false
  - name: LogArchive
    description: >-
      The log archive account. Do not change the name field for this mandatory
      account. Note, the account name key does not need to match the AWS account
      name.
    email: ndx-try-provider+gds-ndx-try-aws-log-archive@dsit.gov.uk
    organizationalUnit: Security
    warm: false
  - name: Audit
    description: >-
      The security audit account (also referred to as the audit account). Do not
      change the name field for this mandatory account. Note, the account name
      key does not need to match the AWS account name.
    email: ndx-try-provider+gds-ndx-try-aws-audit@dsit.gov.uk
    organizationalUnit: Security
    warm: false
workloadAccounts: []
